logging.level.root=info
logging.level.com.example.test=debug

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=hr
spring.datasource.password=hr 

mybatis.type-aliases-package=com.example.test.domain

mybatis.mapper-locations=mappers/**/*.xml

security.headers.frame = false

spring.devtools.livereload.enabled=false

spring.servlet.multipart.location=C:/workspace/ZAAM/zaamimages/
spring.servlet.multipart.max-file-size=10000000

server.port=443
server.ssl.enabled=true
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=zaaaam
server.ssl.key-alias=bns-ssl
server.ssl.key-store-type=PKCS12

room.list.page=6
room.list.group=5